export const GET_USER_ADDRESS_REQUEST="GET_USER_ADDRESS_REQUEST"
export const GET_USER_ADDRESS_SUCCESS="GET_USER_ADDRESS_SUCCESS"
export const GET_USER_ADDRESS_FAILURE="GET_USER_ADDRESS_FAILURE"

export const ADD_USER_ADDRESS_REQUEST="ADD_USER_ADDRESS_REQUEST"
export const ADD_USER_ADDRESS_SUCCESS="ADD_USER_ADDRESS_SUCCESS"
export const ADD_USER_ADDRESS_FAILURE="ADD_USER_ADDRESS_FAILURE"

export const REMOVE_USER_ADDRESS_REQUEST="REMOVE_USER_ADDRESS_REQUEST"
export const REMOVE_USER_ADDRESS_SUCCESS="REMOVE_USER_ADDRESS_SUCCESS"
export const REMOVE_USER_ADDRESS_FAILURE="REMOVE_USER_ADDRESS_FAILURE"


export const UPDATE_USER_ADDRESS_REQUEST="UPDATE_USER_ADDRESS_REQUEST"
export const UPDATE_USER_ADDRESS_SUCCESS="UPDATE_USER_ADDRESS_SUCCESS"
export const UPDATE_USER_ADDRESS_FAILURE="UPDATE_USER_ADDRESS_FAILURE"

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';

export const UPDATE_CART_ITEM_REQUEST = 'UPDATE_CART_ITEM_REQUEST';
export const UPDATE_CART_ITEM_SUCCESS = 'UPDATE_CART_ITEM_SUCCESS';
export const UPDATE_CART_ITEM_FAILURE = 'UPDATE_CART_ITEM_FAILURE';

export const REMOVE_FROM_CART_REQUEST = 'REMOVE_FROM_CART_REQUEST';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAILURE = 'REMOVE_FROM_CART_FAILURE';


